#!/bin/sh
### BEGIN INIT INFO
# Provides:       mscs
# Required-Start: $remote_fs $syslog
# Required-Stop:  $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# chkconfig:      345 50 50
# Description:    Minecraft Server Control Script
### END INIT INFO

# This is a wrapper to msctl that imitates traditional mscs behaviour:
# uses the same default user, config file and location.

# Get executable name
PROG=$(basename $0)

# Setup the default user name.
USER_NAME="minecraft"

# Add Homebrew PATH on macOS so tools are found when running as the minecraft user.
# Also set SSL CA bundle so Perl LWP can verify HTTPS in piped/sudo contexts.
if [ "$(uname -s)" = "Darwin" ]; then
  export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
  if [ -f /etc/ssl/cert.pem ]; then
    export PERL_LWP_SSL_CA_FILE=/etc/ssl/cert.pem
  fi
fi

# Setup the default installation location.
if [ "$(uname -s)" = "Darwin" ]; then
  # Detect Homebrew prefix: Apple Silicon uses /opt/homebrew, Intel uses /usr/local.
  if [ -d /opt/homebrew ]; then
    HOMEBREW_PREFIX=/opt/homebrew
  else
    HOMEBREW_PREFIX=/usr/local
  fi
  LOCATION="$HOMEBREW_PREFIX/var/mscs"
  MSCS_CONF_DIR="$HOMEBREW_PREFIX/etc/mscs"
else
  LOCATION="/opt/mscs"
  MSCS_CONF_DIR="$LOCATION"
fi

# Setup the default location of the mscs.defaults file.
MSCS_DEFAULTS="$MSCS_CONF_DIR/mscs.defaults"

# Run the msctl script.
if [ "$USER_NAME" = "$(whoami)" ]; then
  msctl -p "$PROG" -l "$LOCATION" -c "$MSCS_DEFAULTS" "$@"
else
  cd "$LOCATION" 2>/dev/null || cd /
  sudo PATH="$PATH" PERL_LWP_SSL_CA_FILE="${PERL_LWP_SSL_CA_FILE:-}" -u "$USER_NAME" -H msctl -p "$PROG" -l "$LOCATION" -c "$MSCS_DEFAULTS" "$@"
fi
